<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
		<string>htm</string>
		<string>rb</string>
		<string>php</string>
		<string>tmpl</string>
		<string>txt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--\s*&gt;)
		|^&lt;!--\ \#tminclude\ (?&gt;.*?--&gt;)$
		|&lt;\?(?:php)?.*\b(if|for(each)?|while)\b.+:
		|\{\{?(if|foreach|capture|literal|foreach|php|section|strip)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)&gt;
		|^(?!.*?&lt;!--).*?--\s*&gt;
		|^&lt;!--\ end\ tminclude\ --&gt;$
		|&lt;\?(?:php)?.*\bend(if|for(each)?|while)\b
		|\{\{?/(if|foreach|capture|literal|foreach|php|section|strip)
		|^[^{]*\}
		)</string>
	<key>name</key>
	<string> Nanoc HTML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(-){5}(-\s)*?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.yaml.marker.html.nanoc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-configs-declaration.html.nanoc</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.configs.html.nanoc</string>
			<key>end</key>
			<string>^(-{5})(-\s)*?</string>
			<key>name</key>
			<string>source.yaml.embedded.html.nanoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.nanoc</string>
	<key>uuid</key>
	<string>8DB26D87-5E2F-493F-91F7-D5BF397915C3</string>
</dict>
</plist>
