<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string></string>
	<key>fileTypes</key>
	<array>
		<string>less</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*(?!\*)|\{\s*($|/\*(?!.*?\*/.*\S))</string>
	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string> LESS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.css</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#erb</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.css.less</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@)[a-zA-Z_]\w*</string>
			<key>name</key>
			<string>variable.other.css.less</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>erb</key>
		<dict>
			<key>begin</key>
			<string>&lt;%+(?!&gt;)=?</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>source.ruby.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ruby</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*?(?=%&gt;)</string>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.css.less</string>
	<key>uuid</key>
	<string>9343D324-75A1-4733-A5C0-5D1D4B6182D0</string>
</dict>
</plist>
